spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa

  h2:
    console:
      enabled: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 880757649782-0vcbqh5hc19f9k4j70973b6sel7erlgv.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

  mvc:
    view:
      prefix: "/WEB-INF/views/"
      suffix: ".jsp"

jwt:
  issuer: eogh7204@gmail.com
  secret-key: token-secret-key

# jsp 변경 시 바로 적용
server:
  servlet:
    jsp:
      init-parameters:
        development: true